services:
    xtserver:
      image: ghcr.io/ndw/3.0-test-suite/xproctest:0.9.0
      container_name: xproctests
      ports:
        - 8246:80
      working_dir: /src
      volumes:
        - ./apache2/htdocs:/usr/local/apache2/htdocs
        - ./apache2/cache:/usr/local/apache2/cache
        - ./apache2/cgi-bin:/usr/local/apache2/cgi-bin
        - ./apache2/service:/usr/local/apache2/service
        - ./apache2/conf:/usr/local/apache2/conf
      stdin_open: true
      tty: true
      networks:
        - external_net

    sendriasmtp:
      image: msztolcman/sendria:v2.2.2.0
      container_name: sendriasmtp
      ports:
        - 1025:1025
        - 1080:1080
      stdin_open: true
      tty: true
      environment:
        - MAIL_DRIVER=smtp
        - MAIL_HOST=127.0.0.1
        - MAIL_PORT=1025
        - MAIL_USERNAME=username
        - MAIL_PASSWORD=password
        - MAIL_ENCRYPTION=tcp
        - MAIL_FROM_ADDRESS=nobody@example.com
      networks:
        - external_net

networks:
  external_net: {}
