name: build-specs
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      HAVE_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN != '' }}
      PUBLISH_TESTS_FROM: "master"
      BRANCH_NAME: ${{ github.ref_name }}
    steps:
      - name: Checkout the site
        uses: actions/checkout@v3

      - name: Build
        run: |
          ./gradlew website

      - name: Deploy master to specifications
        if: ${{ env.HAVE_ACCESS_TOKEN == 'true' && github.ref_name == 'master' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          target-folder: /
